<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="generator" content="Hugo 0.46" />

  <title>Creating, Writing, Querying, and Modifying SQL Database from R using odbc, dbplyr, and DBI &middot; goonR blog</title>

  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/pure-min.css">

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/grids-responsive-old-ie-min.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/grids-responsive-min.css">
  <!--<![endif]-->

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="/css/side-menu-old-ie.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="/css/side-menu.css">
  <!--<![endif]-->

  <link rel="stylesheet" href="/css/blackburn.css">

  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">

  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

 
  

  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/androidstudio.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
  
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
  
  <script>hljs.initHighlightingOnLoad();</script>
  

  <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />

  
  

</head>


<body>
<div id="layout">

  
<a href="#menu" id="menuLink" class="menu-link">
  
  <span></span>
</a>
<div id="menu">

  

  <div class="pure-menu">
    <ul class="pure-menu-list">
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="/"><i class='fa fa-home fa-fw'></i>Home</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="/post/"><i class='fa fa-list fa-fw'></i>Posts</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="/about/"><i class='fa fa-user fa-fw'></i>About</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="https://community.rstudio.com/u/tbradley/summary">RStudio Community</a>
      
        </li>
      
    </ul>
  </div>

  <div class="pure-menu social">
  <ul class="pure-menu-list">

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://twitter.com/tycbrad" target="_blank"><i class="fa fa-twitter-square fa-fw"></i>Twitter</a>
    </li>
    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://linkedin.com/in/tyler-bradley-68707292/" target="_blank"><i class="fa fa-linkedin-square fa-fw"></i>LinkedIn</a>
    </li>
    

    

    

    

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://github.com/tbradley1013" target="_blank"><i class="fa fa-github-square fa-fw"></i>GitHub</a>
    </li>
    

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://stackoverflow.com/users/7133355" target="_blank"><i class="fa fa-stack-overflow fa-fw"></i>Stack Overflow</a>
    </li>
    

    

    

    

    

    

    

    

    

    

  </ul>
</div>


  <div>
  <div class="small-print">
    <small></small>
  </div>
  <div class="small-print">
    <small>Built with&nbsp;<a href="https://gohugo.io/" target="_blank">Hugo</a></small>
    <small>Theme&nbsp;<a href="https://github.com/yoshiharuyamashita/blackburn" target="_blank">Blackburn</a></small>
  </div>
</div>

</div>


  <div id="main">


<div class="header">
  <h1>Creating, Writing, Querying, and Modifying SQL Database from R using odbc, dbplyr, and DBI</h1>
  <h2></h2>
</div>
<div class="content">

  <div class="post-meta">

  <div>
    <i class="fa fa-calendar fa-fw"></i>
    <time>26 Aug 2017</time>
  </div>

  

  

  
  
  
  <div>
    <i class="fa fa-tags fa-fw"></i>
    
      <a class="post-taxonomy-tag" href="/tags/tidyverse">tidyverse</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="/tags/sqlite">SQLite</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="/tags/rstats">rstats</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="/tags/dplyr">dplyr</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="/tags/dbi">DBI</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="/tags/odbc">odbc</a>
    
  </div>
  
  

</div>

  <div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Recently, I have been building shiny apps for work. The app that I am currently working on is an interface to a database for storing information about laboratory samples being collected. In addition to building the shiny app for my coworkers to interact with the database, I also was tasked with creating and building the database. I have never build a SQL database from scratch, but luckily the <a href="https://github.com/rstats-db/odbc">odbc</a> and the <a href="https://github.com/rstats-db/DBI">DBI</a> packages make it fairly straight foreward.</p>
<p>Let’s start by loading in the packages that we will need.</p>
<pre class="r"><code>library(DBI)
library(odbc)
library(RSQLite)
library(tidyverse)
library(magrittr)
library(dbplyr)</code></pre>
</div>
<div id="connecting-to-the-database" class="section level1">
<h1>Connecting to the Database</h1>
<p>The <code>dbConnect</code> function from the <code>DBI</code> package allows us to create a SQLite database directly from R. SQLite databases are saved as files in the current working directory with this method. As described in the <code>RSQLite</code> packge vignette, if you simply want to use a temporary database, you can create either an on-disk database or an in-memory database with this same method. For this example, we will create a new SQLite in-memory database</p>
<pre class="r"><code>con &lt;- dbConnect(RSQLite::SQLite(), &quot;:memory:&quot;)</code></pre>
<p>Currently, our database is empty, as can be seen if we use the <code>dbListTables</code> function.</p>
<pre class="r"><code>dbListTables(con)</code></pre>
<pre><code>## character(0)</code></pre>
</div>
<div id="writing-tables-to-database" class="section level1">
<h1>Writing Tables to database</h1>
<p>To add data to this database we will use the <code>dbWriteTable</code> function. First, let’s load in two common datasets, <code>mtcars</code> and <code>diamonds</code>.</p>
<pre class="r"><code>data(&quot;mtcars&quot;)
data(&quot;diamonds&quot;)

mtcars %&lt;&gt;% 
  rownames_to_column()</code></pre>
<p>Now that we have these two data sets loaded into the session, lets write them into the database.</p>
<pre class="r"><code>dbWriteTable(con, &quot;cars&quot;, mtcars)
dbWriteTable(con, &quot;diamonds&quot;, diamonds)

dbListTables(con)</code></pre>
<pre><code>## [1] &quot;cars&quot;     &quot;diamonds&quot;</code></pre>
</div>
<div id="query-the-database" class="section level1">
<h1>Query the Database</h1>
<p>There are several ways that we can query the tables in this database. We can read in the entire table using the <code>dbReadTable</code> function.</p>
<pre class="r"><code>dbReadTable(con, &quot;cars&quot;) %&gt;%
  head(10)</code></pre>
<pre><code>##              rowname  mpg cyl  disp  hp drat    wt  qsec vs am gear carb
## 1          Mazda RX4 21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
## 2      Mazda RX4 Wag 21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
## 3         Datsun 710 22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
## 4     Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
## 5  Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
## 6            Valiant 18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
## 7         Duster 360 14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
## 8          Merc 240D 24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
## 9           Merc 230 22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
## 10          Merc 280 19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4</code></pre>
<p>Alternatively, we can write out a full sql query using the <code>dbGetQuery</code> function.</p>
<pre class="r"><code>dbGetQuery(con, &quot;select * from cars&quot;) %&gt;%
  head(10) </code></pre>
<pre><code>##              rowname  mpg cyl  disp  hp drat    wt  qsec vs am gear carb
## 1          Mazda RX4 21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
## 2      Mazda RX4 Wag 21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
## 3         Datsun 710 22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
## 4     Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
## 5  Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
## 6            Valiant 18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
## 7         Duster 360 14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
## 8          Merc 240D 24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
## 9           Merc 230 22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
## 10          Merc 280 19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4</code></pre>
<p>We can use the <code>microbenchmark</code> package to determine which of these methods is faster. We will measure the time for the diamonds data set as that has nearly 54,000 observations, as opposed to the 32 in the mtcars dataset.</p>
<pre class="r"><code>microbenchmark::microbenchmark(
  read_table = dbReadTable(con, &quot;diamonds&quot;),
  query = dbGetQuery(con, &quot;select * from diamonds&quot;)
)</code></pre>
<pre><code>## Unit: milliseconds
##        expr      min       lq     mean   median       uq      max neval
##  read_table 91.36283 94.55963 115.4623 98.51866 150.1218 175.2671   100
##       query 90.61233 93.50576 111.0308 98.11973 113.0769 181.2567   100</code></pre>
<p>It looks like the <code>dbReadTable</code> method is slightly faster than a full query. However, the real benefit to using <code>dbGetQuery</code> is the ability to write much more complex sql queries. For example, if we want to subset the data, we are able to.</p>
<pre class="r"><code>query &lt;- paste(&quot;select carat, cut, clarity, color, price from diamonds&quot;,
               &quot;where carat &gt; 1 and cut = &#39;Ideal&#39;&quot;)
dbGetQuery(con, query) %&gt;%
  as.tibble()</code></pre>
<pre><code>## # A tibble: 5,662 x 5
##    carat   cut clarity color price
##    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt; &lt;int&gt;
##  1  1.01 Ideal      I1     I  2844
##  2  1.02 Ideal     SI2     H  2856
##  3  1.02 Ideal      I1     I  2872
##  4  1.02 Ideal     SI2     J  2879
##  5  1.01 Ideal      I1     I  2896
##  6  1.02 Ideal      I1     I  2925
##  7  1.14 Ideal     SI1     J  3045
##  8  1.02 Ideal     SI2     H  3142
##  9  1.06 Ideal     SI2     I  3146
## 10  1.02 Ideal     VS2     I  3148
## # ... with 5,652 more rows</code></pre>
<p>This particular query returned just over 10% of the total data with 5,662 rows matching the conditions set. This feature is extremely important when dealing with database that house extremely large amounts of data. Having to query full tables would be extemely unfeasible in most situations.</p>
<p>In addition to writing more complex sql queries, the <code>dbplyr</code> package allows for R users to avoid having to write queries at all. This package allows users to create a reference to the sql table and interact with it using typical <code>dplyr</code> verbs. We can recreate the query above using this method. First we will use the <code>tbl</code> function to create the reference to the diamonds table in the database. Then we will be able to use that reference with all of our favorite <code>dplyr</code> verbs.</p>
<pre class="r"><code>diamonds_tbl &lt;- tbl(con, &quot;diamonds&quot;)

diamonds_tbl %&gt;%
  select(carat, cut, clarity, color, price) %&gt;%
  filter(carat &gt; 1, 
         cut == &quot;Ideal&quot;) %&gt;% 
  collect() %&gt;%
  as.tibble()</code></pre>
<pre><code>## # A tibble: 5,662 x 5
##    carat   cut clarity color price
##    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt; &lt;int&gt;
##  1  1.01 Ideal      I1     I  2844
##  2  1.02 Ideal     SI2     H  2856
##  3  1.02 Ideal      I1     I  2872
##  4  1.02 Ideal     SI2     J  2879
##  5  1.01 Ideal      I1     I  2896
##  6  1.02 Ideal      I1     I  2925
##  7  1.14 Ideal     SI1     J  3045
##  8  1.02 Ideal     SI2     H  3142
##  9  1.06 Ideal     SI2     I  3146
## 10  1.02 Ideal     VS2     I  3148
## # ... with 5,652 more rows</code></pre>
<p>The <code>collect</code> verb is important if you want the full query to be brought into your R session. The <code>dbplyr</code> package uses lazy evaluation and only brings in a portion of the query into your session.</p>
<p>Let’s take a look at how these two methods compare using the <code>microbenchmark</code> package.</p>
<pre class="r"><code>microbenchmark::microbenchmark(
  db_query = dbGetQuery(con, query),
  dbplyr = diamonds_tbl %&gt;%
             select(carat, cut, clarity, color, price) %&gt;%
             filter(carat &gt; 1, 
                    cut == &quot;Ideal&quot;) %&gt;% 
             collect()
)</code></pre>
<pre><code>## Unit: milliseconds
##      expr      min       lq     mean   median       uq      max neval
##  db_query 10.10302 10.30996 10.63014 10.44201 10.60457 15.27123   100
##    dbplyr 51.23319 52.08525 54.66543 53.53378 54.32673 87.69649   100</code></pre>
<p>As we can see, the <code>dbplyr</code> method, while very familiar and potentially easier if you have no experience writing sql queries, takes nearly 6x as long as the straight sql query.</p>
</div>
<div id="modify-tables-in-place" class="section level1">
<h1>Modify Tables in Place</h1>
<p>While there are a lot of blog posts and some great package vignettes about setting up your tables and querying sql databases, there is not too much (that I have seen) about modifying tables in place in your database. There are a few options that are possible when you want to modify a table in a sql database. The first option is to simply query the entire database, make your desired changes using your prefered R tools and then overwrite the table in the database. However, this approach is not practical if you have a large amount of data in your table.</p>
<p>The method that I have found that seems to be fairly straight forward is using the <code>dbSendQuery</code> function. While knowing this function is important, the more important part of this function is knowing what SQL commmads to include in your query. The blog post on <a href="http://www.win-vector.com/blog/2016/02/using-postgresql-in-r/">Win-Vector Blog</a> concerning using PostgreSqL in R shows how you can drop entire tables from your database, and the <code>RSQLite</code> vignette by Hadley Wickham shows how to delete rows that meet certain conditions. However, if you want to modify a table in your database, the sql commands needed are “update” “set”, and “where”. You can see below how we can use these commands.</p>
<pre class="r"><code>update_query &lt;- paste(&quot;update cars&quot;,
                      &quot;set mpg = 20&quot;,
                      &quot;where cyl = 6&quot;)

dbSendQuery(con, update_query)</code></pre>
<pre><code>## &lt;SQLiteResult&gt;
##   SQL  update cars set mpg = 20 where cyl = 6
##   ROWS Fetched: 0 [complete]
##        Changed: 7</code></pre>
<p>We can see that 7 rows were changed in the database. Let’s now query the database and see how the table now looks.</p>
<pre class="r"><code>dbGetQuery(con, &quot;select * from cars&quot;) %&gt;%
  as.tibble()</code></pre>
<pre><code>## # A tibble: 32 x 12
##              rowname   mpg   cyl  disp    hp  drat    wt  qsec    vs    am
##                &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1         Mazda RX4  20.0     6 160.0   110  3.90 2.620 16.46     0     1
##  2     Mazda RX4 Wag  20.0     6 160.0   110  3.90 2.875 17.02     0     1
##  3        Datsun 710  22.8     4 108.0    93  3.85 2.320 18.61     1     1
##  4    Hornet 4 Drive  20.0     6 258.0   110  3.08 3.215 19.44     1     0
##  5 Hornet Sportabout  18.7     8 360.0   175  3.15 3.440 17.02     0     0
##  6           Valiant  20.0     6 225.0   105  2.76 3.460 20.22     1     0
##  7        Duster 360  14.3     8 360.0   245  3.21 3.570 15.84     0     0
##  8         Merc 240D  24.4     4 146.7    62  3.69 3.190 20.00     1     0
##  9          Merc 230  22.8     4 140.8    95  3.92 3.150 22.90     1     0
## 10          Merc 280  20.0     6 167.6   123  3.92 3.440 18.30     1     0
## # ... with 22 more rows, and 2 more variables: gear &lt;dbl&gt;, carb &lt;dbl&gt;</code></pre>
<p>It looks like all of the rows where cyl = 6 have had their mpg changed to 20. While this is a somewhat trivial example, as you would most likely not want to change the results for a data set like this, this can be an incredibly useful feature if you are maintaining a database from R.</p>
<p>You can modify more rows by adding additional arguments to the “set” command and add more conditions by setting additional arguments to the “where” command. For example, we can edit the diamonds table below.</p>
<pre class="r"><code>update_query &lt;- paste(&quot;update diamonds&quot;,
                      &quot;set cut = &#39;new Ideal&#39;,&quot;,
                      &quot;color = &#39;Z&#39;&quot;,
                      &quot;where cut = &#39;Ideal&#39; and&quot;,
                      &quot;color = &#39;E&#39;&quot;)
dbSendQuery(con, update_query)</code></pre>
<pre><code>## &lt;SQLiteResult&gt;
##   SQL  update diamonds set cut = &#39;new Ideal&#39;, color = &#39;Z&#39; where cut = &#39;Ideal&#39; and color = &#39;E&#39;
##   ROWS Fetched: 0 [complete]
##        Changed: 3903</code></pre>
<p>We can see that this changed 3903 rows in the diamonds dataset.</p>
<p>Before we finish, it is imprtant to remember to disconnect from the in-memory database using the <code>dbDisconnect</code> function.</p>
<pre class="r"><code>dbDisconnect(con)</code></pre>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>The <code>DBI</code>, <code>odbc</code>, and <code>dbplyr</code> packages offer an incredible number of tools for interacting with SQL databases of all different kinds. While you are certainly able to navigate through most SQL query problems with only the functions provided in these packages, you can cartainly increase your capabilites by learning some basic SQL commands and how to use them in conjunction with the R functions provided in these packages.</p>
</div>


  
<div class="prev-next-post pure-g">
  <div class="pure-u-1-24" style="text-align: left;">
    
    <a href="/2017/08/10/epl-opening-weekend/"><i class="fa fa-chevron-left"></i></a>
    
  </div>
  <div class="pure-u-10-24">
    
    <nav class="prev">
      <a href="/2017/08/10/epl-opening-weekend/">Exploring English Premier League Historical Match Results</a>
    </nav>
    
  </div>
  <div class="pure-u-2-24">
    &nbsp;
  </div>
  <div class="pure-u-10-24">
    
    <nav class="next">
      <a href="/2018/02/01/pca-in-a-tidy-verse-framework/">PCA in a tidy(verse) framework</a>
    </nav>
    
  </div>
  <div class="pure-u-1-24" style="text-align: right;">
    
    <a href="/2018/02/01/pca-in-a-tidy-verse-framework/"><i class="fa fa-chevron-right"></i></a>
    
  </div>
</div>



  
<div id="disqus_thread"></div>
<script type="text/javascript">

(function() {
    
    
    if (window.location.hostname == "localhost")
        return;

    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    var disqus_shortname = 'goonR-blog';
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


</div>

</div>
</div>
<script src="/js/ui.js"></script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-115670447-2', 'auto');
  ga('send', 'pageview');

</script>





</body>
</html>

